### ISSUE TITLE
Collage creator

### ISSUE THREAD

**Issue by 1alexandra** [FrBrGeorge/python2020#1]
https://github.com/1alexandra/collage

Журавская Александра, 617, @1alexandra
Камалбеков Тимур, 617, @krchmark
Турганбаев Сатбек, 601, @Satbek

**Comment by FrBrGeorge** [comment]
Я не вполне уверен, что тут достаточно работы на троих. Что, собственно, подтерждается текущим состоянием проекта. Можете как-то обосноать?

**Comment by Satbek** [comment]
> Я не вполне уверен, что тут достаточно работы на троих. Что, собственно, подтерждается текущим состоянием проекта. Можете как-то обосноать?
 
Задач достаточно. У нас есть план:
https://github.com/1alexandra/collage/projects/1

Сейчас я добавляю базовые классы для работы с "рабочей зоной",  после этого @krchmark добавит возможность добавлять несколько изображений. Мы считаем , что это самая сложная часть.

Также после https://github.com/1alexandra/collage/pull/15 , можно будет вести разработку параллельно.

Неверно считать, что сейчас над проектом работает только 2 человека, @krchmark дает очень полезные замечания при review. 

Сама идея проекта подразумевает возможность множества фич, так что с объемом работ проблем не должно быть. Самой сложной частью задачи является реализация механизмов динамического изменения коллажа: фотографии отображаются в "ячейках", эти ячейки можно добавлять несколькими способами, а также изменять их размеры. Это не так просто, как кажется, потому что даже выделение обьекта на канвасе приходится реализовывать самостоятельно. После реализации этого функционала, можно будет приступать к другим функциям, по плану среди них кастомные рамки для ячеек и стилизация надписи, но может быть нам придут и другие идеи. Также будут реализованы очередь событий, чтобы действия можно было отменять и возвращать, и сохранение получившегося макета коллажа, чтобы его можно было загрузить и использовать снова.

**Comment by 1alexandra** [comment]
Мы 6 курс, нам нужен зачет до 17 апреля, поэтому мы начали заранее, но работы у нас ещё много.

**Comment by FrBrGeorge** [comment]
Принято, удачи!
Всё ещё до 17 апреля?? А как же неделя выходных, вот это всё?

**Comment by 1alexandra** [comment]
Экзаменационную сессию перенесли, а на счёт зачётной я не знаю, на всякий случай готовилась к худшему.

**Comment by 1alexandra** [comment]
Георгий Владимирович @FrBrGeorge , у нас уже есть рабочая версия со всем необходимым. Посмотрите, пожалуйста.
