### ISSUE TITLE
UnrulyPuzzlePython

### ISSUE THREAD

**Issue by AMMaze** [FrBrGeorge/python2020#11]
Аббас Марат, 618/2
Кинжикеева Дина, 618/2
Комаров Ярослав, 618/1
[https://github.com/AMMaze/UnrulyPuzzlePython](https://github.com/AMMaze/UnrulyPuzzlePython)

**Comment by FrBrGeorge** [comment]
Какая-то ерунда со ссылкой, почему-то не могу по ней перейти
Необходим макет UI, без котрого непонятно, достаточно ли работы для троих

**Comment by AMMaze** [comment]
Добавил макет.

**Comment by FrBrGeorge** [comment]
Хорошо, хотя я сказал бы, что это на _двоих_ всё-таки. Потому, что непонятно, что делает третий. Как бы мешать не начал :). К _объёму_ претензий нет, если что.

**Comment by AMMaze** [comment]
Мы доделали проект.
Наши аккаунты:
Аббас Марат, 618/2 -- @AMMaze
Кинжикеева Дина, 618/2 --  @dinuly23
Комаров Ярослав, 618/1 --  @KomarIar
