### ISSUE TITLE
MDP visualizer

### ISSUE THREAD

**Issue by sserov** [FrBrGeorge/python2020#14]
Авторы:

Иванов Сергей (группа 617) @FortsAndMills
Януш Виктор (группа 617) @justanothercoder
Серов Сергей (группа 617) @sserov

Репозиторий: https://github.com/Scrat-the-Agent/mdp-visualizer

Миграция с GitLab: https://git.cs.msu.ru/agent-scrat/mdp-visualizer

**Comment by FrBrGeorge** [comment]
У меня документация не собирается.

**Comment by sserov** [comment]
> 
> 
> У меня документация не собирается.

Добрый день!

Документацию починили, всё должно собираться.

**Comment by FrBrGeorge** [comment]
[clipboard.txt](https://github.com/FrBrGeorge/python2020/files/4579863/clipboard.txt)
Уже лучше.

Когда у вас дедлайн?

**Comment by sserov** [comment]
Насколько я понимаю, без учета недели пересдач --- 10-е мая.

**Comment by justanothercoder** [comment]
Добрый день!

Документация, кажется всё-таки собралась, но ошибку импорта setup.py поправили.

**Comment by FrBrGeorge** [comment]
Ок. А что у вас с pylint/pyflake/вот этим всем? А то требование такое есть)
Hint: на это можно забить, на самом деле.

**Comment by justanothercoder** [comment]
Вообще каждый пользовался встроенным в IDE чекером, но ради требования добавили .pylintrc отдельно, так что можно теперь код проверить и так.
