### ISSUE TITLE
Isolation game

### ISSUE THREAD

**Issue by Zamony** [FrBrGeorge/python2020#6]
Никита Мочалов, 525
Павел Жуков, 525
Владислав Семак, 524
Алла Дорофеева, 524

https://github.com/Zamony/isolation

**Comment by FrBrGeorge** [comment]
Будьте добры, нарисуйте хотя бы примерную модель всего UI. Пока неясно, достаточен ли фронт работ для четверых.

**Comment by Zamony** [comment]
> Будьте добры, нарисуйте хотя бы примерную модель всего UI. Пока неясно, достаточен ли фронт работ для четверых.

Добавили примерную модель всего UI.

У самой игры не очень сложный графический интерфейс. Но мы делаем ставку не на него, а на функциональность: реализация AI (минимакс), нескольких уровней сложности, и, скорее всего, сетевой версии игры. Конечно же, будет локализация для русского и английского языков.

Еще хотели узнать, к какому числу это все должно быть готово?

**Comment by FrBrGeorge** [comment]
К какому числу, _мне_ не очень важно. А вот вашей учебной части может быть не всё равно:)

**Comment by Zamony** [comment]
@FrBrGeorge а в каком виде должна быть документация, если мы делаем игру, которая распространяется в бинарном виде? Просто описания в README недостаточно?

**Comment by FrBrGeorge** [comment]
Я _надеюсь_, что неправильно понял вас про «бинарный вид» :)
Нужно документирование _кода_ и выгонка этой документации куда-нибудь. Нужны инструкции мне по установке и тестированию. Это всё может лежать в гите. Если есть какая-то in-game документация, её надо носить с собой.
