### ISSUE TITLE
Sokoban

### ISSUE THREAD

**Issue by MariaNekrasova** [FrBrGeorge/python2020#7]
Конопаткин Олег (524 группа)
Коробова Екатерина (524 группа)
Некрасова Мария (511 группа)
https://github.com/Konopatkin-OV/MSU_Python_Project_Prac_2020

**Comment by FrBrGeorge** [comment]
Будьте добры, нарисуйте хотя бы примерную модель всего UI. Пока неясно, достаточен ли фронт работ для троих

**Comment by katekorobova** [comment]
Добавлена примерная модель GUI.

**Comment by MariaNekrasova** [comment]
Проект готов к сдаче.

**Comment by FrBrGeorge** [comment]
Ох, я тут все сроки пропинал. Найдите меня в Telegram, @FrBrGeorge.

**Comment by FrBrGeorge** [comment]
Отл
