### ISSUE TITLE
Client-Server Image Processing

### ISSUE THREAD

**Issue by whatcouldbepizza** [FrBrGeorge/python2020#8]
Участники:
1. Волков Дмитрий (601 группа)
2. Карнаухов Валерий (601 группа)
Репозиторий: https://github.com/Dalgex/Client-Server-Image-Filter

**Comment by FrBrGeorge** [comment]
Нет постановки задачи

**Comment by whatcouldbepizza** [comment]
Прошу прощения, забыли отписаться сюда. Постановку задачи и краткое описание добавили. В ближайшее время планируем также добавить в readme инструкцию по использованию серверной и клиентской частей.

**Comment by FrBrGeorge** [comment]
Коротковато для постановки, но времени уже совсем нет, надеюсь, вы понимаете, что делать)

**Comment by whatcouldbepizza** [comment]
Добрый день!
Мы уже подготовили весь функционал, который планировался. Хотели уточнить, в каком формате происходит сдача? Нужно ли нам как-то показывать и защищать проект?

**Comment by whatcouldbepizza** [comment]
Добрый день!
К сожалению, нас уже начинает дёргать кафедра (для 6 курса сессия раньше), могли бы Вы посмотреть нашу работу?

**Comment by FrBrGeorge** [comment]
Сегодня сделаю
