### ISSUE TITLE
getdrunk-telegram-bot

### ISSUE THREAD

**Issue by soboleva-daria** [FrBrGeorge/python2020#9]
Участники:

    Мария Яворская (517 группа)
    Николай Скачков (517 группа)
    Алексей Письменный (517 группа)
    Дарья Соболева (517 группа)

Репозиторий: https://github.com/soboleva-daria/getdrunk-telegram-bot

**Comment by FrBrGeorge** [comment]
Отсутствует описание задачи. Её должно быть достаточно для четверых..

**Comment by soboleva-daria** [comment]
Добавили, TODO будем заполнять в процессе работы. Мария Яворская и Алексей Письменный работают над предобрабткой данных, обучением модели/моделей, заморозкой модели для последующего применения на данных пользователя. Я и Николай Скачков работаем над структурой самого бота и деплоем его на heroku. Ну и парсингом того, что получили в нужный для предсказания модели формат. Возможно будем выдавать еще какую-то общую информацию по коктейлю (картинку или интересный факт, например, кем был создан).

**Comment by FrBrGeorge** [comment]
Это пользовательское описание, а мне нужна архитрекура самого проекта. Пока я не в состоянии оценить, много это или мало. Ну, и история коммитов пока что не вдохновляет:)

**Comment by soboleva-daria** [comment]
А про дату дедлайна можете сказать? :)

**Comment by FrBrGeorge** [comment]
_Мне_, в целом, всё равно:) А вот вашей учебной чати, возможно, нет))

**Comment by soboleva-daria** [comment]
Здравствуйте, мы дописали почти всю необходимую функциональность, добавили внятный README, собираемую документацию и тесты. Посмотрите пожалуйста. Дорабатываем еще подборы рецептов. Все остальные команды работают.

**Comment by soboleva-daria** [comment]
Здравствуйте, не могли бы Вы пожалуйста глянуть наш репозиторий? Учебная часть хочет, чтобы у нас была проставлена оценка до 28 мая 2020. Спасибо!

**Comment by FrBrGeorge** [comment]
Так, вот я срок и пропинал ::(
Ещё не поздно?

**Comment by soboleva-daria** [comment]
Нет!

**Comment by FrBrGeorge** [comment]
Вам зачёт или с оценкой? Also, может в TG? @FrBrGeorge
